{{- if .Values.podSecurityPolicy.create -}}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
    apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
    kubernetes.io/description: This policy grants the minimum amount of privilege
      necessary to run non-privileged kube-system pods. This policy is not intended
      for use outside of kube-system, and may include further restrictions in the
      future.
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: runtime/default,docker/default
    seccomp.security.alpha.kubernetes.io/defaultProfileName: docker/default
  name: {{ include "healthcheck.fullname" . }}.psp
spec:
  allowPrivilegeEscalation: false
  allowedCapabilities:
  - SETPCAP
  - MKNOD
  - AUDIT_WRITE
  - CHOWN
  - NET_RAW
  - DAC_OVERRIDE
  - FOWNER
  - FSETID
  - KILL
  - SETGID
  - SETUID
  - NET_ADMIN
  - NET_BIND_SERVICE
  - CAP_NET_ADMIN
  - SYS_CHROOT
  - SETFCAP
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - emptyDir
  - configMap
  - secret
  - projected
  - downwardAPI
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "healthcheck.fullname" . }}
  labels:
    {{- include "healthcheck.labels" . | nindent 4 }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ include "healthcheck.fullname" . }}.psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "healthcheck.fullname" . }}
  labels:
    {{- include "healthcheck.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "healthcheck.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "healthcheck.serviceAccountName" . }}
{{- end }}

