
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "healthcheck.serviceAccountName" . }}
  labels:
    {{- include "healthcheck.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ include "healthcheck.gcpAccountName" . }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.iamServiceAccount.create -}}
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.iamServiceAccount.project }}
  name: {{ include "healthcheck.iamAccountName" . }}
spec:
  displayName: Service account for healthcheck
---
{{- range $k, $v := .Values.iamServiceAccount.polices }}
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: {{ include "healthcheck.iamAccountName" $ }}-pm{{ $k }}
spec:
  member: serviceAccount:{{ include "healthcheck.gcpAccountName" $ }}
  role: {{ $v.role }}
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: {{ if $v.project }} project/{{ $v.project }} {{ else }} project/{{ $.Values.iamServiceAccount.project }} {{ end }}
---
{{- end }}
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccountKey
metadata:
  name: {{ include "healthcheck.iamAccountName" . }}-key
spec:
  publicKeyType: TYPE_X509_PEM_FILE
  keyAlgorithm: KEY_ALG_RSA_2048
  privateKeyType: TYPE_GOOGLE_CREDENTIALS_FILE
  serviceAccountRef:
    name: {{ include "healthcheck.iamAccountName" . }}
{{- end }}
