name: 'Release'

on:
  workflow_dispatch: {}
  push:
    branches:
    - develop
    - staging
    - prod
    paths:
      - 'src/**'
      - 'config/**'
      - 'charts/**'
      - yarn.lock
      - package.json
jobs:
  release:
    name: 'Release'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Semantic Release
      id: semantic
      uses: cycjimmy/semantic-release-action@v2.5.4
      with:
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}